version: '3.9'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2048M'

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
