services:
  db:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./database:/var/lib/postgresql/data